### ISSUE TITLE
Emoji keyboard

### ISSUE THREAD

**Issue by pchauhan** [zeuxisoo/android-emoji-keyboard#1]
Hello 
Nice tutorial,
But when i pressed cartoon (Symbolic) character it always show some japanise font .
How can i solve this issue? 

Thanks
Parag

**Comment by zeuxisoo** [comment]
Hello, Because the cartoon character is not support by native fonts.
If you want to display it, maybe you need to install some fonts

**Comment by pchauhan** [comment]
Thanks Zeuxisoo , can we programatically  install fonts in emoji apk ?

**Comment by zeuxisoo** [comment]
Based on my knowledge, If you would like to install emoji fonts, the device must rooted.

**Comment by pchauhan** [comment]
Ok Thank you very much Zeuxisoo ,  last question can we put image directly in Edittext when perticular key pressed in anywhere in mobile using our keyboard?

**Comment by zeuxisoo** [comment]
Um, It may work, but you may need to extends the Edittext UI object to make this change
