### ISSUE TITLE
How to use this with Stickers instead of Keycode?

### ISSUE THREAD

**Issue by darmie** [zeuxisoo/android-emoji-keyboard#3]
Hi I am trying to achieve a stickers keyboard like this 

![screenshot_20161108-211238](https://cloud.githubusercontent.com/assets/848002/20496904/583b8dec-b027-11e6-894a-e37ffd5ceaee.png)

**Comment by zeuxisoo** [comment]
Hello, Thank you for your question. 

The aim of the project is trying to custom emoji keyboard for a system. 
In your question, you may need to implement keyboard layout for your app. 

So, I think the activity will like this, and trigger the keyboard view by some action:

``` xml
<StickerKeyboardLayout>
    <LinearLayout>
        <AppBarLayout>
            <Toolbar></Toolbar>
        </AppBarLayout>
        <ListView>
        </ListView>
    </LinearLayout>
</StickerKeyboardLayout>
```
